#!/usr/bin/env bash
# World wide web
domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "54.147.172.31"
  domain_information "$1" "54.90.177.85"
  domain_information "$1" "54.91.200.176"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
