#!/usr/bin/env bash
# Installs Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html;
}
" > /etc/nginx/sites-available/default;
sudo service nginx restart

